vim.opt.expandtab = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.termguicolors = true
vim.opt.shortmess = vim.opt.shortmess .. 'c'
vim.opt.updatetime = 100
vim.opt.encoding = "utf-8"
vim.opt.nobackup = true
vim.opt.noswapfile = true
vim.opt.noundofile = true
vim.opt.signcolumn = "no"
